spring:
  application:
    name: user-server
  profiles:
    active: local
    include: db
  server:
    port: 8080
    shutdown: graceful
    tomcat:
      basedir: .
      connection-timeout: 60s
      threads:
        max: 2000
      accesslog:
        # %h %l %u %t %r %s %b 默认
        #pattern see https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Logging
        pattern: '%h %l %u %t %r %s %b %D'
        enabled: ${acclog.enabled}
        max-days: 10
app:
  login:
    access-token-expire: 2h
    session-endpoint: ${app.login.session-endpoint}
    wx-app-id: wx76561e919bb4753a
    wx-secret: 9946a3c0127a810648307815edf1f8fb