// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

public interface JwtInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.jwt.JwtInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 主题，一般放关键业务标识字段，如用户ID
   * </pre>
   *
   * <code>string sub = 1;</code>
   * @return The sub.
   */
  java.lang.String getSub();
  /**
   * <pre>
   * 主题，一般放关键业务标识字段，如用户ID
   * </pre>
   *
   * <code>string sub = 1;</code>
   * @return The bytes for sub.
   */
  com.google.protobuf.ByteString
      getSubBytes();

  /**
   * <pre>
   * 签发者，一般可以放业务标识，如登录，短信验证
   * </pre>
   *
   * <code>string iss = 2;</code>
   * @return The iss.
   */
  java.lang.String getIss();
  /**
   * <pre>
   * 签发者，一般可以放业务标识，如登录，短信验证
   * </pre>
   *
   * <code>string iss = 2;</code>
   * @return The bytes for iss.
   */
  com.google.protobuf.ByteString
      getIssBytes();

  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @return A list containing the aud.
   */
  java.util.List<java.lang.String>
      getAudList();
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @return The count of aud.
   */
  int getAudCount();
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @param index The index of the element to return.
   * @return The aud at the given index.
   */
  java.lang.String getAud(int index);
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the aud at the given index.
   */
  com.google.protobuf.ByteString
      getAudBytes(int index);

  /**
   * <pre>
   * 过期时间戳（秒）
   * </pre>
   *
   * <code>int64 exp = 4;</code>
   * @return The exp.
   */
  long getExp();

  /**
   * <pre>
   * 不早于某个时间使用，时间戳（秒）
   * </pre>
   *
   * <code>int64 nbf = 5;</code>
   * @return The nbf.
   */
  long getNbf();

  /**
   * <pre>
   * 签发时间
   * </pre>
   *
   * <code>int64 iat = 6;</code>
   * @return The iat.
   */
  long getIat();

  /**
   * <pre>
   * jwt token id
   * </pre>
   *
   * <code>string jti = 7;</code>
   * @return The jti.
   */
  java.lang.String getJti();
  /**
   * <pre>
   * jwt token id
   * </pre>
   *
   * <code>string jti = 7;</code>
   * @return The bytes for jti.
   */
  com.google.protobuf.ByteString
      getJtiBytes();

  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  int getAttributesCount();
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  /* nullable */
java.lang.String getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  java.lang.String getAttributesOrThrow(
      java.lang.String key);
}
