// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

/**
 * Protobuf type {@code com.seezoon.jwt.JwtInfo}
 */
public final class JwtInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.seezoon.jwt.JwtInfo)
    JwtInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JwtInfo.newBuilder() to construct.
  private JwtInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JwtInfo() {
    sub_ = "";
    iss_ = "";
    aud_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    jti_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JwtInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 8:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.seezoon.stub.jwt.JwtInfo.class, com.seezoon.stub.jwt.JwtInfo.Builder.class);
  }

  public static final int SUB_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sub_ = "";
  /**
   * <pre>
   * 主题，一般放关键业务标识字段，如用户ID
   * </pre>
   *
   * <code>string sub = 1;</code>
   * @return The sub.
   */
  @java.lang.Override
  public java.lang.String getSub() {
    java.lang.Object ref = sub_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sub_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 主题，一般放关键业务标识字段，如用户ID
   * </pre>
   *
   * <code>string sub = 1;</code>
   * @return The bytes for sub.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubBytes() {
    java.lang.Object ref = sub_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sub_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object iss_ = "";
  /**
   * <pre>
   * 签发者，一般可以放业务标识，如登录，短信验证
   * </pre>
   *
   * <code>string iss = 2;</code>
   * @return The iss.
   */
  @java.lang.Override
  public java.lang.String getIss() {
    java.lang.Object ref = iss_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iss_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 签发者，一般可以放业务标识，如登录，短信验证
   * </pre>
   *
   * <code>string iss = 2;</code>
   * @return The bytes for iss.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIssBytes() {
    java.lang.Object ref = iss_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iss_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList aud_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @return A list containing the aud.
   */
  public com.google.protobuf.ProtocolStringList
      getAudList() {
    return aud_;
  }
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @return The count of aud.
   */
  public int getAudCount() {
    return aud_.size();
  }
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @param index The index of the element to return.
   * @return The aud at the given index.
   */
  public java.lang.String getAud(int index) {
    return aud_.get(index);
  }
  /**
   * <pre>
   * 观众，一般代表接收方
   * </pre>
   *
   * <code>repeated string aud = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the aud at the given index.
   */
  public com.google.protobuf.ByteString
      getAudBytes(int index) {
    return aud_.getByteString(index);
  }

  public static final int EXP_FIELD_NUMBER = 4;
  private long exp_ = 0L;
  /**
   * <pre>
   * 过期时间戳（秒）
   * </pre>
   *
   * <code>int64 exp = 4;</code>
   * @return The exp.
   */
  @java.lang.Override
  public long getExp() {
    return exp_;
  }

  public static final int NBF_FIELD_NUMBER = 5;
  private long nbf_ = 0L;
  /**
   * <pre>
   * 不早于某个时间使用，时间戳（秒）
   * </pre>
   *
   * <code>int64 nbf = 5;</code>
   * @return The nbf.
   */
  @java.lang.Override
  public long getNbf() {
    return nbf_;
  }

  public static final int IAT_FIELD_NUMBER = 6;
  private long iat_ = 0L;
  /**
   * <pre>
   * 签发时间
   * </pre>
   *
   * <code>int64 iat = 6;</code>
   * @return The iat.
   */
  @java.lang.Override
  public long getIat() {
    return iat_;
  }

  public static final int JTI_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jti_ = "";
  /**
   * <pre>
   * jwt token id
   * </pre>
   *
   * <code>string jti = 7;</code>
   * @return The jti.
   */
  @java.lang.Override
  public java.lang.String getJti() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jti_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * jwt token id
   * </pre>
   *
   * <code>string jti = 7;</code>
   * @return The bytes for jti.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJtiBytes() {
    java.lang.Object ref = jti_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jti_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 8;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> attributes_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }
  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override
  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 自定义属性，不能包含上述字段
   * </pre>
   *
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override
  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sub_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sub_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iss_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iss_);
    }
    for (int i = 0; i < aud_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, aud_.getRaw(i));
    }
    if (exp_ != 0L) {
      output.writeInt64(4, exp_);
    }
    if (nbf_ != 0L) {
      output.writeInt64(5, nbf_);
    }
    if (iat_ != 0L) {
      output.writeInt64(6, iat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jti_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, jti_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        8);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sub_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sub_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iss_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iss_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < aud_.size(); i++) {
        dataSize += computeStringSizeNoTag(aud_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAudList().size();
    }
    if (exp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, exp_);
    }
    if (nbf_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, nbf_);
    }
    if (iat_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, iat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jti_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, jti_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, attributes__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.seezoon.stub.jwt.JwtInfo)) {
      return super.equals(obj);
    }
    com.seezoon.stub.jwt.JwtInfo other = (com.seezoon.stub.jwt.JwtInfo) obj;

    if (!getSub()
        .equals(other.getSub())) return false;
    if (!getIss()
        .equals(other.getIss())) return false;
    if (!getAudList()
        .equals(other.getAudList())) return false;
    if (getExp()
        != other.getExp()) return false;
    if (getNbf()
        != other.getNbf()) return false;
    if (getIat()
        != other.getIat()) return false;
    if (!getJti()
        .equals(other.getJti())) return false;
    if (!internalGetAttributes().equals(
        other.internalGetAttributes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUB_FIELD_NUMBER;
    hash = (53 * hash) + getSub().hashCode();
    hash = (37 * hash) + ISS_FIELD_NUMBER;
    hash = (53 * hash) + getIss().hashCode();
    if (getAudCount() > 0) {
      hash = (37 * hash) + AUD_FIELD_NUMBER;
      hash = (53 * hash) + getAudList().hashCode();
    }
    hash = (37 * hash) + EXP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExp());
    hash = (37 * hash) + NBF_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNbf());
    hash = (37 * hash) + IAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIat());
    hash = (37 * hash) + JTI_FIELD_NUMBER;
    hash = (53 * hash) + getJti().hashCode();
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.seezoon.stub.jwt.JwtInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.seezoon.stub.jwt.JwtInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.jwt.JwtInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.seezoon.stub.jwt.JwtInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.seezoon.jwt.JwtInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.seezoon.jwt.JwtInfo)
      com.seezoon.stub.jwt.JwtInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 8:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seezoon.stub.jwt.JwtInfo.class, com.seezoon.stub.jwt.JwtInfo.Builder.class);
    }

    // Construct using com.seezoon.stub.jwt.JwtInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sub_ = "";
      iss_ = "";
      aud_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      exp_ = 0L;
      nbf_ = 0L;
      iat_ = 0L;
      jti_ = "";
      internalGetMutableAttributes().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_JwtInfo_descriptor;
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.JwtInfo getDefaultInstanceForType() {
      return com.seezoon.stub.jwt.JwtInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.JwtInfo build() {
      com.seezoon.stub.jwt.JwtInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.JwtInfo buildPartial() {
      com.seezoon.stub.jwt.JwtInfo result = new com.seezoon.stub.jwt.JwtInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.seezoon.stub.jwt.JwtInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sub_ = sub_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.iss_ = iss_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        aud_.makeImmutable();
        result.aud_ = aud_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.exp_ = exp_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.nbf_ = nbf_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.iat_ = iat_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.jti_ = jti_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.attributes_ = internalGetAttributes();
        result.attributes_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.seezoon.stub.jwt.JwtInfo) {
        return mergeFrom((com.seezoon.stub.jwt.JwtInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.seezoon.stub.jwt.JwtInfo other) {
      if (other == com.seezoon.stub.jwt.JwtInfo.getDefaultInstance()) return this;
      if (!other.getSub().isEmpty()) {
        sub_ = other.sub_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIss().isEmpty()) {
        iss_ = other.iss_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.aud_.isEmpty()) {
        if (aud_.isEmpty()) {
          aud_ = other.aud_;
          bitField0_ |= 0x00000004;
        } else {
          ensureAudIsMutable();
          aud_.addAll(other.aud_);
        }
        onChanged();
      }
      if (other.getExp() != 0L) {
        setExp(other.getExp());
      }
      if (other.getNbf() != 0L) {
        setNbf(other.getNbf());
      }
      if (other.getIat() != 0L) {
        setIat(other.getIat());
      }
      if (!other.getJti().isEmpty()) {
        jti_ = other.jti_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      bitField0_ |= 0x00000080;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sub_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              iss_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAudIsMutable();
              aud_.add(s);
              break;
            } // case 26
            case 32: {
              exp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              nbf_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              iat_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              jti_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAttributes().getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sub_ = "";
    /**
     * <pre>
     * 主题，一般放关键业务标识字段，如用户ID
     * </pre>
     *
     * <code>string sub = 1;</code>
     * @return The sub.
     */
    public java.lang.String getSub() {
      java.lang.Object ref = sub_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sub_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 主题，一般放关键业务标识字段，如用户ID
     * </pre>
     *
     * <code>string sub = 1;</code>
     * @return The bytes for sub.
     */
    public com.google.protobuf.ByteString
        getSubBytes() {
      java.lang.Object ref = sub_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sub_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 主题，一般放关键业务标识字段，如用户ID
     * </pre>
     *
     * <code>string sub = 1;</code>
     * @param value The sub to set.
     * @return This builder for chaining.
     */
    public Builder setSub(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sub_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 主题，一般放关键业务标识字段，如用户ID
     * </pre>
     *
     * <code>string sub = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSub() {
      sub_ = getDefaultInstance().getSub();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 主题，一般放关键业务标识字段，如用户ID
     * </pre>
     *
     * <code>string sub = 1;</code>
     * @param value The bytes for sub to set.
     * @return This builder for chaining.
     */
    public Builder setSubBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sub_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object iss_ = "";
    /**
     * <pre>
     * 签发者，一般可以放业务标识，如登录，短信验证
     * </pre>
     *
     * <code>string iss = 2;</code>
     * @return The iss.
     */
    public java.lang.String getIss() {
      java.lang.Object ref = iss_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iss_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 签发者，一般可以放业务标识，如登录，短信验证
     * </pre>
     *
     * <code>string iss = 2;</code>
     * @return The bytes for iss.
     */
    public com.google.protobuf.ByteString
        getIssBytes() {
      java.lang.Object ref = iss_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iss_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 签发者，一般可以放业务标识，如登录，短信验证
     * </pre>
     *
     * <code>string iss = 2;</code>
     * @param value The iss to set.
     * @return This builder for chaining.
     */
    public Builder setIss(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      iss_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 签发者，一般可以放业务标识，如登录，短信验证
     * </pre>
     *
     * <code>string iss = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIss() {
      iss_ = getDefaultInstance().getIss();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 签发者，一般可以放业务标识，如登录，短信验证
     * </pre>
     *
     * <code>string iss = 2;</code>
     * @param value The bytes for iss to set.
     * @return This builder for chaining.
     */
    public Builder setIssBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      iss_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList aud_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAudIsMutable() {
      if (!aud_.isModifiable()) {
        aud_ = new com.google.protobuf.LazyStringArrayList(aud_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @return A list containing the aud.
     */
    public com.google.protobuf.ProtocolStringList
        getAudList() {
      aud_.makeImmutable();
      return aud_;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @return The count of aud.
     */
    public int getAudCount() {
      return aud_.size();
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param index The index of the element to return.
     * @return The aud at the given index.
     */
    public java.lang.String getAud(int index) {
      return aud_.get(index);
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the aud at the given index.
     */
    public com.google.protobuf.ByteString
        getAudBytes(int index) {
      return aud_.getByteString(index);
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param index The index to set the value at.
     * @param value The aud to set.
     * @return This builder for chaining.
     */
    public Builder setAud(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAudIsMutable();
      aud_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param value The aud to add.
     * @return This builder for chaining.
     */
    public Builder addAud(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAudIsMutable();
      aud_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param values The aud to add.
     * @return This builder for chaining.
     */
    public Builder addAllAud(
        java.lang.Iterable<java.lang.String> values) {
      ensureAudIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, aud_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAud() {
      aud_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 观众，一般代表接收方
     * </pre>
     *
     * <code>repeated string aud = 3;</code>
     * @param value The bytes of the aud to add.
     * @return This builder for chaining.
     */
    public Builder addAudBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAudIsMutable();
      aud_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long exp_ ;
    /**
     * <pre>
     * 过期时间戳（秒）
     * </pre>
     *
     * <code>int64 exp = 4;</code>
     * @return The exp.
     */
    @java.lang.Override
    public long getExp() {
      return exp_;
    }
    /**
     * <pre>
     * 过期时间戳（秒）
     * </pre>
     *
     * <code>int64 exp = 4;</code>
     * @param value The exp to set.
     * @return This builder for chaining.
     */
    public Builder setExp(long value) {

      exp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 过期时间戳（秒）
     * </pre>
     *
     * <code>int64 exp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      exp_ = 0L;
      onChanged();
      return this;
    }

    private long nbf_ ;
    /**
     * <pre>
     * 不早于某个时间使用，时间戳（秒）
     * </pre>
     *
     * <code>int64 nbf = 5;</code>
     * @return The nbf.
     */
    @java.lang.Override
    public long getNbf() {
      return nbf_;
    }
    /**
     * <pre>
     * 不早于某个时间使用，时间戳（秒）
     * </pre>
     *
     * <code>int64 nbf = 5;</code>
     * @param value The nbf to set.
     * @return This builder for chaining.
     */
    public Builder setNbf(long value) {

      nbf_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不早于某个时间使用，时间戳（秒）
     * </pre>
     *
     * <code>int64 nbf = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNbf() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nbf_ = 0L;
      onChanged();
      return this;
    }

    private long iat_ ;
    /**
     * <pre>
     * 签发时间
     * </pre>
     *
     * <code>int64 iat = 6;</code>
     * @return The iat.
     */
    @java.lang.Override
    public long getIat() {
      return iat_;
    }
    /**
     * <pre>
     * 签发时间
     * </pre>
     *
     * <code>int64 iat = 6;</code>
     * @param value The iat to set.
     * @return This builder for chaining.
     */
    public Builder setIat(long value) {

      iat_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 签发时间
     * </pre>
     *
     * <code>int64 iat = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIat() {
      bitField0_ = (bitField0_ & ~0x00000020);
      iat_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object jti_ = "";
    /**
     * <pre>
     * jwt token id
     * </pre>
     *
     * <code>string jti = 7;</code>
     * @return The jti.
     */
    public java.lang.String getJti() {
      java.lang.Object ref = jti_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jti_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * jwt token id
     * </pre>
     *
     * <code>string jti = 7;</code>
     * @return The bytes for jti.
     */
    public com.google.protobuf.ByteString
        getJtiBytes() {
      java.lang.Object ref = jti_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jti_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * jwt token id
     * </pre>
     *
     * <code>string jti = 7;</code>
     * @param value The jti to set.
     * @return This builder for chaining.
     */
    public Builder setJti(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jti_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * jwt token id
     * </pre>
     *
     * <code>string jti = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearJti() {
      jti_ = getDefaultInstance().getJti();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * jwt token id
     * </pre>
     *
     * <code>string jti = 7;</code>
     * @param value The bytes for jti to set.
     * @return This builder for chaining.
     */
    public Builder setJtiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jti_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableAttributes() {
      if (attributes_ == null) {
        attributes_ = com.google.protobuf.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return attributes_;
    }
    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override
    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearAttributes() {
      bitField0_ = (bitField0_ & ~0x00000080);
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableAttributes() {
      bitField0_ |= 0x00000080;
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <pre>
     * 自定义属性，不能包含上述字段
     * </pre>
     *
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000080;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.seezoon.jwt.JwtInfo)
  }

  // @@protoc_insertion_point(class_scope:com.seezoon.jwt.JwtInfo)
  private static final com.seezoon.stub.jwt.JwtInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.seezoon.stub.jwt.JwtInfo();
  }

  public static com.seezoon.stub.jwt.JwtInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JwtInfo>
      PARSER = new com.google.protobuf.AbstractParser<JwtInfo>() {
    @java.lang.Override
    public JwtInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JwtInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JwtInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.seezoon.stub.jwt.JwtInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

