// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

public final class JwtOuterClass {
  private JwtOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_JwtInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_JwtInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_SignReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_SignReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_SignResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_SignResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_VerifyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_VerifyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seezoon_jwt_VerifyResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_seezoon_jwt_VerifyResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjwt.proto\022\017com.seezoon.jwt\032\027validate/v" +
      "alidate.proto\"\325\001\n\007JwtInfo\022\013\n\003sub\030\001 \001(\t\022\013" +
      "\n\003iss\030\002 \001(\t\022\013\n\003aud\030\003 \003(\t\022\013\n\003exp\030\004 \001(\003\022\013\n" +
      "\003nbf\030\005 \001(\003\022\013\n\003iat\030\006 \001(\003\022\013\n\003jti\030\007 \001(\t\022<\n\n" +
      "attributes\030\010 \003(\0132(.com.seezoon.jwt.JwtIn" +
      "fo.AttributesEntry\0321\n\017AttributesEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\">\n\007SignReq" +
      "\0223\n\007jwtInfo\030\001 \001(\0132\030.com.seezoon.jwt.JwtI" +
      "nfoB\010\372B\005\212\001\002\020\001\"\031\n\010SignResp\022\r\n\005token\030\001 \001(\t" +
      "\"#\n\tVerifyReq\022\026\n\005token\030\001 \001(\tB\007\372B\004r\002\020\024\"F\n" +
      "\nVerifyResp\022\r\n\005valid\030\001 \001(\010\022)\n\007jwtInfo\030\002 " +
      "\001(\0132\030.com.seezoon.jwt.JwtInfo2\211\001\n\003Jwt\022=\n" +
      "\004Sign\022\030.com.seezoon.jwt.SignReq\032\031.com.se" +
      "ezoon.jwt.SignResp\"\000\022C\n\006Verify\022\032.com.see" +
      "zoon.jwt.VerifyReq\032\033.com.seezoon.jwt.Ver" +
      "ifyResp\"\000BG\n\024com.seezoon.stub.jwtP\001Z-git" +
      "hub.com/seezoon-go-stub/jwt-server-stub;" +
      "pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_com_seezoon_jwt_JwtInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seezoon_jwt_JwtInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_JwtInfo_descriptor,
        new java.lang.String[] { "Sub", "Iss", "Aud", "Exp", "Nbf", "Iat", "Jti", "Attributes", });
    internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_descriptor =
      internal_static_com_seezoon_jwt_JwtInfo_descriptor.getNestedTypes().get(0);
    internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_JwtInfo_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_seezoon_jwt_SignReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_seezoon_jwt_SignReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_SignReq_descriptor,
        new java.lang.String[] { "JwtInfo", });
    internal_static_com_seezoon_jwt_SignResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_seezoon_jwt_SignResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_SignResp_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_com_seezoon_jwt_VerifyReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_seezoon_jwt_VerifyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_VerifyReq_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_com_seezoon_jwt_VerifyResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_seezoon_jwt_VerifyResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_seezoon_jwt_VerifyResp_descriptor,
        new java.lang.String[] { "Valid", "JwtInfo", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
