// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

public interface SignRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.jwt.SignResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
