// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

/**
 * Protobuf type {@code com.seezoon.jwt.VerifyResp}
 */
public final class VerifyResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.seezoon.jwt.VerifyResp)
    VerifyRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifyResp.newBuilder() to construct.
  private VerifyResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifyResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerifyResp();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_VerifyResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_VerifyResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.seezoon.stub.jwt.VerifyResp.class, com.seezoon.stub.jwt.VerifyResp.Builder.class);
  }

  private int bitField0_;
  public static final int VALID_FIELD_NUMBER = 1;
  private boolean valid_ = false;
  /**
   * <pre>
   * 不合法，过期等都为false
   * </pre>
   *
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  @java.lang.Override
  public boolean getValid() {
    return valid_;
  }

  public static final int JWTINFO_FIELD_NUMBER = 2;
  private com.seezoon.stub.jwt.JwtInfo jwtInfo_;
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   * @return Whether the jwtInfo field is set.
   */
  @java.lang.Override
  public boolean hasJwtInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   * @return The jwtInfo.
   */
  @java.lang.Override
  public com.seezoon.stub.jwt.JwtInfo getJwtInfo() {
    return jwtInfo_ == null ? com.seezoon.stub.jwt.JwtInfo.getDefaultInstance() : jwtInfo_;
  }
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   */
  @java.lang.Override
  public com.seezoon.stub.jwt.JwtInfoOrBuilder getJwtInfoOrBuilder() {
    return jwtInfo_ == null ? com.seezoon.stub.jwt.JwtInfo.getDefaultInstance() : jwtInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valid_ != false) {
      output.writeBool(1, valid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getJwtInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, valid_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getJwtInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.seezoon.stub.jwt.VerifyResp)) {
      return super.equals(obj);
    }
    com.seezoon.stub.jwt.VerifyResp other = (com.seezoon.stub.jwt.VerifyResp) obj;

    if (getValid()
        != other.getValid()) return false;
    if (hasJwtInfo() != other.hasJwtInfo()) return false;
    if (hasJwtInfo()) {
      if (!getJwtInfo()
          .equals(other.getJwtInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getValid());
    if (hasJwtInfo()) {
      hash = (37 * hash) + JWTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getJwtInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.seezoon.stub.jwt.VerifyResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.seezoon.stub.jwt.VerifyResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.seezoon.stub.jwt.VerifyResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.seezoon.stub.jwt.VerifyResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.seezoon.jwt.VerifyResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.seezoon.jwt.VerifyResp)
      com.seezoon.stub.jwt.VerifyRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_VerifyResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_VerifyResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seezoon.stub.jwt.VerifyResp.class, com.seezoon.stub.jwt.VerifyResp.Builder.class);
    }

    // Construct using com.seezoon.stub.jwt.VerifyResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJwtInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      valid_ = false;
      jwtInfo_ = null;
      if (jwtInfoBuilder_ != null) {
        jwtInfoBuilder_.dispose();
        jwtInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.seezoon.stub.jwt.JwtOuterClass.internal_static_com_seezoon_jwt_VerifyResp_descriptor;
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.VerifyResp getDefaultInstanceForType() {
      return com.seezoon.stub.jwt.VerifyResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.VerifyResp build() {
      com.seezoon.stub.jwt.VerifyResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.seezoon.stub.jwt.VerifyResp buildPartial() {
      com.seezoon.stub.jwt.VerifyResp result = new com.seezoon.stub.jwt.VerifyResp(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.seezoon.stub.jwt.VerifyResp result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.valid_ = valid_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.jwtInfo_ = jwtInfoBuilder_ == null
            ? jwtInfo_
            : jwtInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.seezoon.stub.jwt.VerifyResp) {
        return mergeFrom((com.seezoon.stub.jwt.VerifyResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.seezoon.stub.jwt.VerifyResp other) {
      if (other == com.seezoon.stub.jwt.VerifyResp.getDefaultInstance()) return this;
      if (other.getValid() != false) {
        setValid(other.getValid());
      }
      if (other.hasJwtInfo()) {
        mergeJwtInfo(other.getJwtInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              valid_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getJwtInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean valid_ ;
    /**
     * <pre>
     * 不合法，过期等都为false
     * </pre>
     *
     * <code>bool valid = 1;</code>
     * @return The valid.
     */
    @java.lang.Override
    public boolean getValid() {
      return valid_;
    }
    /**
     * <pre>
     * 不合法，过期等都为false
     * </pre>
     *
     * <code>bool valid = 1;</code>
     * @param value The valid to set.
     * @return This builder for chaining.
     */
    public Builder setValid(boolean value) {

      valid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不合法，过期等都为false
     * </pre>
     *
     * <code>bool valid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      valid_ = false;
      onChanged();
      return this;
    }

    private com.seezoon.stub.jwt.JwtInfo jwtInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.seezoon.stub.jwt.JwtInfo, com.seezoon.stub.jwt.JwtInfo.Builder, com.seezoon.stub.jwt.JwtInfoOrBuilder> jwtInfoBuilder_;
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     * @return Whether the jwtInfo field is set.
     */
    public boolean hasJwtInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     * @return The jwtInfo.
     */
    public com.seezoon.stub.jwt.JwtInfo getJwtInfo() {
      if (jwtInfoBuilder_ == null) {
        return jwtInfo_ == null ? com.seezoon.stub.jwt.JwtInfo.getDefaultInstance() : jwtInfo_;
      } else {
        return jwtInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public Builder setJwtInfo(com.seezoon.stub.jwt.JwtInfo value) {
      if (jwtInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jwtInfo_ = value;
      } else {
        jwtInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public Builder setJwtInfo(
        com.seezoon.stub.jwt.JwtInfo.Builder builderForValue) {
      if (jwtInfoBuilder_ == null) {
        jwtInfo_ = builderForValue.build();
      } else {
        jwtInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public Builder mergeJwtInfo(com.seezoon.stub.jwt.JwtInfo value) {
      if (jwtInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          jwtInfo_ != null &&
          jwtInfo_ != com.seezoon.stub.jwt.JwtInfo.getDefaultInstance()) {
          getJwtInfoBuilder().mergeFrom(value);
        } else {
          jwtInfo_ = value;
        }
      } else {
        jwtInfoBuilder_.mergeFrom(value);
      }
      if (jwtInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public Builder clearJwtInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      jwtInfo_ = null;
      if (jwtInfoBuilder_ != null) {
        jwtInfoBuilder_.dispose();
        jwtInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public com.seezoon.stub.jwt.JwtInfo.Builder getJwtInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getJwtInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    public com.seezoon.stub.jwt.JwtInfoOrBuilder getJwtInfoOrBuilder() {
      if (jwtInfoBuilder_ != null) {
        return jwtInfoBuilder_.getMessageOrBuilder();
      } else {
        return jwtInfo_ == null ?
            com.seezoon.stub.jwt.JwtInfo.getDefaultInstance() : jwtInfo_;
      }
    }
    /**
     * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.seezoon.stub.jwt.JwtInfo, com.seezoon.stub.jwt.JwtInfo.Builder, com.seezoon.stub.jwt.JwtInfoOrBuilder> 
        getJwtInfoFieldBuilder() {
      if (jwtInfoBuilder_ == null) {
        jwtInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.seezoon.stub.jwt.JwtInfo, com.seezoon.stub.jwt.JwtInfo.Builder, com.seezoon.stub.jwt.JwtInfoOrBuilder>(
                getJwtInfo(),
                getParentForChildren(),
                isClean());
        jwtInfo_ = null;
      }
      return jwtInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.seezoon.jwt.VerifyResp)
  }

  // @@protoc_insertion_point(class_scope:com.seezoon.jwt.VerifyResp)
  private static final com.seezoon.stub.jwt.VerifyResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.seezoon.stub.jwt.VerifyResp();
  }

  public static com.seezoon.stub.jwt.VerifyResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifyResp>
      PARSER = new com.google.protobuf.AbstractParser<VerifyResp>() {
    @java.lang.Override
    public VerifyResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerifyResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifyResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.seezoon.stub.jwt.VerifyResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

