// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jwt.proto

// Protobuf Java Version: 3.25.3
package com.seezoon.stub.jwt;

public interface VerifyRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.seezoon.jwt.VerifyResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 不合法，过期等都为false
   * </pre>
   *
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   * @return Whether the jwtInfo field is set.
   */
  boolean hasJwtInfo();
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   * @return The jwtInfo.
   */
  com.seezoon.stub.jwt.JwtInfo getJwtInfo();
  /**
   * <code>.com.seezoon.jwt.JwtInfo jwtInfo = 2;</code>
   */
  com.seezoon.stub.jwt.JwtInfoOrBuilder getJwtInfoOrBuilder();
}
